=== Youconix/miniature-happiness/admin/modules/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <!-- Declare a special element type, for later. -->
  <xs:simpleType name="non-empty-string">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- <module> (Top level) -->
  <xs:element name="module">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="non-empty-string"/>
        <xs:element name="author" type="non-empty-string"/>
        <xs:element name="description" type="non-empty-string"/>
        <xs:element name="version">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <!-- The element named 'version' must not be a negative. -->
              <xs:minInclusive value="0"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="install" type="xs:string"/>
        <xs:element name="upgrade" type="xs:string"/>
        <xs:element name="deinstall" type="xs:string"/>
        <xs:element name="title" type="non-empty-string"/>
        <xs:element name="js" type="xs:string"/>
        <xs:element name="css" type="xs:string"/>
        <!-- The element below has to occur at least once. No less. -->
        <xs:element ref="block" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- <module><block> -->
  <xs:element name="block">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="id" type="xs:string"/>
        <!-- The element below isn't required, but may only occur 5 times at most. -->
        <xs:element ref="link" minOccurs="0" maxOccurs="5"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <!-- <module><block><link> -->
  <xs:element name="link">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="id" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Youconix/miniature-happiness/src/admin/modules/statistics/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../settings.xsd">
  <name>Statistics</name>
  <author>Youconix</author>
  <description>Statistics module for the framework Miniature-happiness</description>
  <version>1.0</version>
  <install>install.php</install>
  <upgrade></upgrade>
  <deinstall>deinstall.php</deinstall>
  <title>system/menu/statistics</title>
  <css>statistics.css</css>
  <block>
    <title>system/admin/statistics/settings</title>
    <id>admin_statistics_settings</id>
    <path>admin_statistics_settings</path>
  </block>
  <block>
    <title>system/admin/statistics/visitors</title>
    <id>admin_statistics_visitors</id>
    <path>admin_statistics_visitors</path>
  </block>
  <block>
    <title>system/admin/statistics/visitors_hours</title>
    <id>admin_statistics_visitors_hours</id>
    <path>admin_statistics_visitors_hour</path>
  </block>
  <block>
    <title>system/admin/statistics/os</title>
    <id>admin_statistics_os</id>
    <path>admin_statistics_os</path>
  </block>
  <block>
    <title>system/admin/statistics/browsers</title>
    <id>admin_statistics_browsers</id>
    <path>admin_statistics_browsers</path>
  </block>
  <block>
    <title>system/admin/statistics/screen_colors</title>
    <id>admin_statistics_screen_colors</id>
    <path>admin_statistics_colors</path>
  </block>
  <block>
    <title>system/admin/statistics/screen_sizes</title>
    <id>admin_statistics_screen_sizes</id>
    <path>admin_statistics_sizes</path>
  </block>
  <block>
    <title>system/admin/statistics/references</title>
    <id>admin_statistics_references</id>
    <path>admin_statistics_references</path>
  </block>
  <block>
    <title>system/admin/statistics/pages</title>
    <id>admin_statistics_pages</id>
    <path>admin_statistics_pages</path>
  </block>
</module>
